import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import QRCode from "qrcode";

export type ExportOptions = {
  /** DOM element id holding the calculator markup (inputs + results) */
  elementId: string;
  /** Tool title in both languages */
  title: { ar: string; en: string };
  /** Standard reference (IFRS/IAS/...) optional */
  standard?: { ar: string; en: string };
  /** Short description / about */
  about?: { ar: string; en: string };
  /** Current language for chrome strings */
  lang: "ar" | "en";
  /** Optional file name (without extension) */
  fileName?: string;
};

const BRAND = {
  name: "Ahmed Elmadni — Smart Accounting Tools",
  gold: "#b8862e",
  goldSoft: "#d7aa52",
  ink: "#0b1220",
  soft: "#475569",
  line: "#d7aa52",
};

/** Capture a DOM element to a high-resolution canvas using a temporary light theme. */
async function captureLight(el: HTMLElement): Promise<HTMLCanvasElement> {
  document.body.classList.add("pdf-export-mode");
  // give the browser a tick to apply styles
  await new Promise((r) => setTimeout(r, 50));
  try {
    const canvas = await html2canvas(el, {
      backgroundColor: "#ffffff",
      scale: Math.min(2, (window.devicePixelRatio || 1) * 1.5),
      useCORS: true,
      logging: false,
      windowWidth: el.scrollWidth,
    });
    return canvas;
  } finally {
    document.body.classList.remove("pdf-export-mode");
  }
}

export async function exportToolReportPdf(opts: ExportOptions): Promise<void> {
  const el = document.getElementById(opts.elementId);
  if (!el) throw new Error(`Element #${opts.elementId} not found`);

  const isAR = opts.lang === "ar";
  const t = {
    inputs: isAR ? "المدخلات والنتائج" : "Inputs & Results",
    generatedAt: isAR ? "تم الإنشاء في" : "Generated at",
    scan: isAR ? "امسح للوصول للأداة" : "Scan to open this tool",
    standard: isAR ? "المعيار المرتبط" : "Related standard",
    footer: "Generated by Ahmed Elmadni Accounting Tools",
    notes: isAR ? "ملاحظة" : "Notes",
    page: isAR ? "صفحة" : "Page",
    of: isAR ? "من" : "of",
  };

  const canvas = await captureLight(el);
  const imgData = canvas.toDataURL("image/jpeg", 0.95);

  const pdf = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const margin = 14;

  // ---------- Header ----------
  const drawHeader = () => {
    pdf.setFillColor(11, 18, 32);
    pdf.rect(0, 0, pageW, 22, "F");
    pdf.setFillColor(184, 134, 46);
    pdf.rect(0, 22, pageW, 1.2, "F");
    pdf.setTextColor(243, 210, 138);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(11);
    pdf.text(BRAND.name, margin, 10);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(215, 170, 82);
    pdf.text("ahmedelmadni.com", margin, 16);
    // Right side: timestamp
    const ts = new Date().toLocaleString(isAR ? "ar-EG" : "en-US");
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(8);
    pdf.text(`${t.generatedAt}: ${ts}`, pageW - margin, 10, { align: "right" });
  };

  // ---------- Footer ----------
  const drawFooter = (page: number, total: number) => {
    pdf.setDrawColor(215, 170, 82);
    pdf.setLineWidth(0.3);
    pdf.line(margin, pageH - 14, pageW - margin, pageH - 14);
    pdf.setFont("helvetica", "italic");
    pdf.setFontSize(8);
    pdf.setTextColor(100, 116, 139);
    pdf.text(t.footer, margin, pageH - 8);
    pdf.text(`${t.page} ${page} ${t.of} ${total}`, pageW - margin, pageH - 8, { align: "right" });
  };

  drawHeader();

  // ---------- Title block ----------
  let y = 32;
  pdf.setTextColor(11, 18, 32);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(16);
  pdf.text(opts.title.en, margin, y);
  if (opts.title.ar) {
    y += 6;
    pdf.setFontSize(12);
    pdf.setTextColor(120, 85, 20);
    pdf.text(opts.title.ar, margin, y);
  }

  if (opts.standard) {
    y += 6;
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(71, 85, 105);
    pdf.text(`${t.standard}: ${opts.standard.en} · ${opts.standard.ar}`, margin, y);
  }

  if (opts.about) {
    y += 6;
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(71, 85, 105);
    const aboutText = opts.about.en;
    const lines = pdf.splitTextToSize(aboutText, pageW - margin * 2);
    pdf.text(lines, margin, y);
    y += lines.length * 4;
  }

  y += 4;
  pdf.setDrawColor(215, 170, 82);
  pdf.setLineWidth(0.3);
  pdf.line(margin, y, pageW - margin, y);
  y += 5;

  // Section label
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(10);
  pdf.setTextColor(184, 134, 46);
  pdf.text(t.inputs, margin, y);
  y += 4;

  // ---------- Place captured image, paginating if needed ----------
  const usableW = pageW - margin * 2;
  const imgW = usableW;
  const imgH = (canvas.height * imgW) / canvas.width;

  const firstAreaTop = y + 2;
  const lastAreaBottom = pageH - 20; // leave room for footer + QR
  const firstAreaH = lastAreaBottom - firstAreaTop;

  if (imgH <= firstAreaH) {
    pdf.addImage(imgData, "JPEG", margin, firstAreaTop, imgW, imgH);
  } else {
    // Slice the canvas into A4-fitting strips
    let sliceHpx = (firstAreaH * canvas.width) / imgW;
    let renderedPx = 0;
    let topMm = firstAreaTop;
    while (renderedPx < canvas.height) {
      const remainingPx = canvas.height - renderedPx;
      const takePx = Math.min(sliceHpx, remainingPx);
      const sliceCanvas = document.createElement("canvas");
      sliceCanvas.width = canvas.width;
      sliceCanvas.height = takePx;
      const ctx = sliceCanvas.getContext("2d");
      if (!ctx) break;
      ctx.fillStyle = "#ffffff";
      ctx.fillRect(0, 0, sliceCanvas.width, sliceCanvas.height);
      ctx.drawImage(canvas, 0, renderedPx, canvas.width, takePx, 0, 0, canvas.width, takePx);
      const sliceData = sliceCanvas.toDataURL("image/jpeg", 0.95);
      const drawnHmm = (takePx * imgW) / canvas.width;
      pdf.addImage(sliceData, "JPEG", margin, topMm, imgW, drawnHmm);
      renderedPx += takePx;
      if (renderedPx < canvas.height) {
        pdf.addPage();
        drawHeader();
        topMm = 28;
        const availMm = pageH - 20 - topMm;
        sliceHpx = (availMm * canvas.width) / imgW;
      }
    }
  }


  // ---------- QR + footer on the last page ----------
  const totalPages = pdf.getNumberOfPages();
  // Add QR + finalize footers on every page
  const url = typeof window !== "undefined" ? window.location.href : "";
  let qrData = "";
  try {
    qrData = await QRCode.toDataURL(url, { margin: 0, width: 256, color: { dark: "#0b1220", light: "#ffffff" } });
  } catch {
    qrData = "";
  }

  for (let p = 1; p <= totalPages; p++) {
    pdf.setPage(p);
    drawFooter(p, totalPages);
  }

  // Put QR on the last page above footer line
  if (qrData) {
    pdf.setPage(totalPages);
    const qrSize = 24;
    const qrX = pageW - margin - qrSize;
    const qrY = pageH - 14 - qrSize - 2;
    pdf.setFillColor(255, 255, 255);
    pdf.rect(qrX - 2, qrY - 2, qrSize + 4, qrSize + 4, "F");
    pdf.addImage(qrData, "PNG", qrX, qrY, qrSize, qrSize);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(7);
    pdf.setTextColor(100, 116, 139);
    pdf.text(t.scan, qrX + qrSize / 2, qrY + qrSize + 3, { align: "center" });
  }

  const safe = (s: string) => s.replace(/[^a-zA-Z0-9-_]+/g, "_");
  const name = opts.fileName || safe(`${opts.title.en}-${new Date().toISOString().slice(0, 10)}`);
  pdf.save(`${name}.pdf`);
}
