/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RequestServiceRouteImport } from './routes/request-service'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as ToolsToolIdRouteImport } from './routes/tools.$toolId'
import { Route as LibraryCoursesRouteImport } from './routes/library.courses'
import { Route as LibraryBooksRouteImport } from './routes/library.books'
import { Route as LibraryArticlesRouteImport } from './routes/library.articles'
import { Route as ApiOfficeAiRouteImport } from './routes/api/office-ai'
import { Route as ApiCvEnhanceRouteImport } from './routes/api/cv-enhance'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedDeclarationsRouteImport } from './routes/_authenticated/declarations'
import { Route as KnowledgeCategorySlugIndexRouteImport } from './routes/knowledge.$categorySlug.index'
import { Route as KnowledgeCategorySlugArticleSlugRouteImport } from './routes/knowledge.$categorySlug.$articleSlug'
import { Route as AuthenticatedAdminLibraryRouteImport } from './routes/_authenticated/admin.library'
import { Route as AuthenticatedAdminKnowledgeRouteImport } from './routes/_authenticated/admin.knowledge'
import { Route as ApiPublicHooksGenerateArticlesRouteImport } from './routes/api/public/hooks/generate-articles'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestServiceRoute = RequestServiceRouteImport.update({
  id: '/request-service',
  path: '/request-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolIdRoute = ToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryCoursesRoute = LibraryCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryBooksRoute = LibraryBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryArticlesRoute = LibraryArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => LibraryRoute,
} as any)
const ApiOfficeAiRoute = ApiOfficeAiRouteImport.update({
  id: '/api/office-ai',
  path: '/api/office-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCvEnhanceRoute = ApiCvEnhanceRouteImport.update({
  id: '/api/cv-enhance',
  path: '/api/cv-enhance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDeclarationsRoute =
  AuthenticatedDeclarationsRouteImport.update({
    id: '/declarations',
    path: '/declarations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const KnowledgeCategorySlugIndexRoute =
  KnowledgeCategorySlugIndexRouteImport.update({
    id: '/knowledge/$categorySlug/',
    path: '/knowledge/$categorySlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const KnowledgeCategorySlugArticleSlugRoute =
  KnowledgeCategorySlugArticleSlugRouteImport.update({
    id: '/knowledge/$categorySlug/$articleSlug',
    path: '/knowledge/$categorySlug/$articleSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminLibraryRoute =
  AuthenticatedAdminLibraryRouteImport.update({
    id: '/admin/library',
    path: '/admin/library',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKnowledgeRoute =
  AuthenticatedAdminKnowledgeRouteImport.update({
    id: '/admin/knowledge',
    path: '/admin/knowledge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksGenerateArticlesRoute =
  ApiPublicHooksGenerateArticlesRouteImport.update({
    id: '/api/public/hooks/generate-articles',
    path: '/api/public/hooks/generate-articles',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/certifications': typeof CertificationsRoute
  '/experience': typeof ExperienceRoute
  '/library': typeof LibraryRouteWithChildren
  '/request-service': typeof RequestServiceRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/declarations': typeof AuthenticatedDeclarationsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cv-enhance': typeof ApiCvEnhanceRoute
  '/api/office-ai': typeof ApiOfficeAiRoute
  '/library/articles': typeof LibraryArticlesRoute
  '/library/books': typeof LibraryBooksRoute
  '/library/courses': typeof LibraryCoursesRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/knowledge/$categorySlug/$articleSlug': typeof KnowledgeCategorySlugArticleSlugRoute
  '/knowledge/$categorySlug/': typeof KnowledgeCategorySlugIndexRoute
  '/api/public/hooks/generate-articles': typeof ApiPublicHooksGenerateArticlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/certifications': typeof CertificationsRoute
  '/experience': typeof ExperienceRoute
  '/request-service': typeof RequestServiceRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/declarations': typeof AuthenticatedDeclarationsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cv-enhance': typeof ApiCvEnhanceRoute
  '/api/office-ai': typeof ApiOfficeAiRoute
  '/library/articles': typeof LibraryArticlesRoute
  '/library/books': typeof LibraryBooksRoute
  '/library/courses': typeof LibraryCoursesRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/library': typeof LibraryIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/knowledge/$categorySlug/$articleSlug': typeof KnowledgeCategorySlugArticleSlugRoute
  '/knowledge/$categorySlug': typeof KnowledgeCategorySlugIndexRoute
  '/api/public/hooks/generate-articles': typeof ApiPublicHooksGenerateArticlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/certifications': typeof CertificationsRoute
  '/experience': typeof ExperienceRoute
  '/library': typeof LibraryRouteWithChildren
  '/request-service': typeof RequestServiceRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/_authenticated/declarations': typeof AuthenticatedDeclarationsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cv-enhance': typeof ApiCvEnhanceRoute
  '/api/office-ai': typeof ApiOfficeAiRoute
  '/library/articles': typeof LibraryArticlesRoute
  '/library/books': typeof LibraryBooksRoute
  '/library/courses': typeof LibraryCoursesRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/_authenticated/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/_authenticated/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/knowledge/$categorySlug/$articleSlug': typeof KnowledgeCategorySlugArticleSlugRoute
  '/knowledge/$categorySlug/': typeof KnowledgeCategorySlugIndexRoute
  '/api/public/hooks/generate-articles': typeof ApiPublicHooksGenerateArticlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/certifications'
    | '/experience'
    | '/library'
    | '/request-service'
    | '/services'
    | '/sitemap.xml'
    | '/skills'
    | '/declarations'
    | '/api/chat'
    | '/api/cv-enhance'
    | '/api/office-ai'
    | '/library/articles'
    | '/library/books'
    | '/library/courses'
    | '/tools/$toolId'
    | '/knowledge/'
    | '/library/'
    | '/tools/'
    | '/admin/knowledge'
    | '/admin/library'
    | '/knowledge/$categorySlug/$articleSlug'
    | '/knowledge/$categorySlug/'
    | '/api/public/hooks/generate-articles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/certifications'
    | '/experience'
    | '/request-service'
    | '/services'
    | '/sitemap.xml'
    | '/skills'
    | '/declarations'
    | '/api/chat'
    | '/api/cv-enhance'
    | '/api/office-ai'
    | '/library/articles'
    | '/library/books'
    | '/library/courses'
    | '/tools/$toolId'
    | '/knowledge'
    | '/library'
    | '/tools'
    | '/admin/knowledge'
    | '/admin/library'
    | '/knowledge/$categorySlug/$articleSlug'
    | '/knowledge/$categorySlug'
    | '/api/public/hooks/generate-articles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/certifications'
    | '/experience'
    | '/library'
    | '/request-service'
    | '/services'
    | '/sitemap.xml'
    | '/skills'
    | '/_authenticated/declarations'
    | '/api/chat'
    | '/api/cv-enhance'
    | '/api/office-ai'
    | '/library/articles'
    | '/library/books'
    | '/library/courses'
    | '/tools/$toolId'
    | '/knowledge/'
    | '/library/'
    | '/tools/'
    | '/_authenticated/admin/knowledge'
    | '/_authenticated/admin/library'
    | '/knowledge/$categorySlug/$articleSlug'
    | '/knowledge/$categorySlug/'
    | '/api/public/hooks/generate-articles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CertificationsRoute: typeof CertificationsRoute
  ExperienceRoute: typeof ExperienceRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  RequestServiceRoute: typeof RequestServiceRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkillsRoute: typeof SkillsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCvEnhanceRoute: typeof ApiCvEnhanceRoute
  ApiOfficeAiRoute: typeof ApiOfficeAiRoute
  ToolsToolIdRoute: typeof ToolsToolIdRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  KnowledgeCategorySlugArticleSlugRoute: typeof KnowledgeCategorySlugArticleSlugRoute
  KnowledgeCategorySlugIndexRoute: typeof KnowledgeCategorySlugIndexRoute
  ApiPublicHooksGenerateArticlesRoute: typeof ApiPublicHooksGenerateArticlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-service': {
      id: '/request-service'
      path: '/request-service'
      fullPath: '/request-service'
      preLoaderRoute: typeof RequestServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolId': {
      id: '/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof ToolsToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/courses': {
      id: '/library/courses'
      path: '/courses'
      fullPath: '/library/courses'
      preLoaderRoute: typeof LibraryCoursesRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/books': {
      id: '/library/books'
      path: '/books'
      fullPath: '/library/books'
      preLoaderRoute: typeof LibraryBooksRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/articles': {
      id: '/library/articles'
      path: '/articles'
      fullPath: '/library/articles'
      preLoaderRoute: typeof LibraryArticlesRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/api/office-ai': {
      id: '/api/office-ai'
      path: '/api/office-ai'
      fullPath: '/api/office-ai'
      preLoaderRoute: typeof ApiOfficeAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cv-enhance': {
      id: '/api/cv-enhance'
      path: '/api/cv-enhance'
      fullPath: '/api/cv-enhance'
      preLoaderRoute: typeof ApiCvEnhanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/declarations': {
      id: '/_authenticated/declarations'
      path: '/declarations'
      fullPath: '/declarations'
      preLoaderRoute: typeof AuthenticatedDeclarationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/knowledge/$categorySlug/': {
      id: '/knowledge/$categorySlug/'
      path: '/knowledge/$categorySlug'
      fullPath: '/knowledge/$categorySlug/'
      preLoaderRoute: typeof KnowledgeCategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$categorySlug/$articleSlug': {
      id: '/knowledge/$categorySlug/$articleSlug'
      path: '/knowledge/$categorySlug/$articleSlug'
      fullPath: '/knowledge/$categorySlug/$articleSlug'
      preLoaderRoute: typeof KnowledgeCategorySlugArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/library': {
      id: '/_authenticated/admin/library'
      path: '/admin/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AuthenticatedAdminLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/knowledge': {
      id: '/_authenticated/admin/knowledge'
      path: '/admin/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/generate-articles': {
      id: '/api/public/hooks/generate-articles'
      path: '/api/public/hooks/generate-articles'
      fullPath: '/api/public/hooks/generate-articles'
      preLoaderRoute: typeof ApiPublicHooksGenerateArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDeclarationsRoute: typeof AuthenticatedDeclarationsRoute
  AuthenticatedAdminKnowledgeRoute: typeof AuthenticatedAdminKnowledgeRoute
  AuthenticatedAdminLibraryRoute: typeof AuthenticatedAdminLibraryRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDeclarationsRoute: AuthenticatedDeclarationsRoute,
  AuthenticatedAdminKnowledgeRoute: AuthenticatedAdminKnowledgeRoute,
  AuthenticatedAdminLibraryRoute: AuthenticatedAdminLibraryRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LibraryRouteChildren {
  LibraryArticlesRoute: typeof LibraryArticlesRoute
  LibraryBooksRoute: typeof LibraryBooksRoute
  LibraryCoursesRoute: typeof LibraryCoursesRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryArticlesRoute: LibraryArticlesRoute,
  LibraryBooksRoute: LibraryBooksRoute,
  LibraryCoursesRoute: LibraryCoursesRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CertificationsRoute: CertificationsRoute,
  ExperienceRoute: ExperienceRoute,
  LibraryRoute: LibraryRouteWithChildren,
  RequestServiceRoute: RequestServiceRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkillsRoute: SkillsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCvEnhanceRoute: ApiCvEnhanceRoute,
  ApiOfficeAiRoute: ApiOfficeAiRoute,
  ToolsToolIdRoute: ToolsToolIdRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  KnowledgeCategorySlugArticleSlugRoute: KnowledgeCategorySlugArticleSlugRoute,
  KnowledgeCategorySlugIndexRoute: KnowledgeCategorySlugIndexRoute,
  ApiPublicHooksGenerateArticlesRoute: ApiPublicHooksGenerateArticlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
