/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as ToolsToolIdRouteImport } from './routes/tools.$toolId'
import { Route as ApiCvEnhanceRouteImport } from './routes/api/cv-enhance'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedDeclarationsRouteImport } from './routes/_authenticated/declarations'
import { Route as KnowledgeCategorySlugIndexRouteImport } from './routes/knowledge.$categorySlug.index'
import { Route as KnowledgeCategorySlugArticleSlugRouteImport } from './routes/knowledge.$categorySlug.$articleSlug'
import { Route as AuthenticatedAdminLibraryRouteImport } from './routes/_authenticated/admin.library'
import { Route as AuthenticatedAdminKnowledgeRouteImport } from './routes/_authenticated/admin.knowledge'
import { Route as ApiPublicHooksGenerateArticlesRouteImport } from './routes/api/public/hooks/generate-articles'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolIdRoute = ToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCvEnhanceRoute = ApiCvEnhanceRouteImport.update({
  id: '/api/cv-enhance',
  path: '/api/cv-enhance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDeclarationsRoute =
  AuthenticatedDeclarationsRouteImport.update({
    id: '/declarations',
    path: '/declarations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const KnowledgeCategorySlugIndexRoute =
  KnowledgeCategorySlugIndexRouteImport.update({
    id: '/knowledge/$categorySlug/',
    path: '/knowledge/$categorySlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const KnowledgeCategorySlugArticleSlugRoute =
  KnowledgeCategorySlugArticleSlugRouteImport.update({
    id: '/knowledge/$categorySlug/$articleSlug',
    path: '/knowledge/$categorySlug/$articleSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminLibraryRoute =
  AuthenticatedAdminLibraryRouteImport.update({
    id: '/admin/library',
    path: '/admin/library',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKnowledgeRoute =
  AuthenticatedAdminKnowledgeRouteImport.update({
    id: '/admin/knowledge',
    path: '/admin/knowledge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksGenerateArticlesRoute =
  ApiPublicHooksGenerateArticlesRouteImport.update({
    id: '/api/public/hooks/generate-articles',
    path: '/api/public/hooks/generate-articles',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/declarations': typeof AuthenticatedDeclarationsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cv-enhance': typeof ApiCvEnhanceRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/knowledge/$categorySlug/$articleSlug': typeof KnowledgeCategorySlugArticleSlugRoute
  '/knowledge/$categorySlug/': typeof KnowledgeCategorySlugIndexRoute
  '/api/public/hooks/generate-articles': typeof ApiPublicHooksGenerateArticlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/declarations': typeof AuthenticatedDeclarationsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cv-enhance': typeof ApiCvEnhanceRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/knowledge/$categorySlug/$articleSlug': typeof KnowledgeCategorySlugArticleSlugRoute
  '/knowledge/$categorySlug': typeof KnowledgeCategorySlugIndexRoute
  '/api/public/hooks/generate-articles': typeof ApiPublicHooksGenerateArticlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/declarations': typeof AuthenticatedDeclarationsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cv-enhance': typeof ApiCvEnhanceRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/_authenticated/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/_authenticated/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/knowledge/$categorySlug/$articleSlug': typeof KnowledgeCategorySlugArticleSlugRoute
  '/knowledge/$categorySlug/': typeof KnowledgeCategorySlugIndexRoute
  '/api/public/hooks/generate-articles': typeof ApiPublicHooksGenerateArticlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/library'
    | '/sitemap.xml'
    | '/declarations'
    | '/api/chat'
    | '/api/cv-enhance'
    | '/tools/$toolId'
    | '/knowledge/'
    | '/tools/'
    | '/admin/knowledge'
    | '/admin/library'
    | '/knowledge/$categorySlug/$articleSlug'
    | '/knowledge/$categorySlug/'
    | '/api/public/hooks/generate-articles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/library'
    | '/sitemap.xml'
    | '/declarations'
    | '/api/chat'
    | '/api/cv-enhance'
    | '/tools/$toolId'
    | '/knowledge'
    | '/tools'
    | '/admin/knowledge'
    | '/admin/library'
    | '/knowledge/$categorySlug/$articleSlug'
    | '/knowledge/$categorySlug'
    | '/api/public/hooks/generate-articles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/library'
    | '/sitemap.xml'
    | '/_authenticated/declarations'
    | '/api/chat'
    | '/api/cv-enhance'
    | '/tools/$toolId'
    | '/knowledge/'
    | '/tools/'
    | '/_authenticated/admin/knowledge'
    | '/_authenticated/admin/library'
    | '/knowledge/$categorySlug/$articleSlug'
    | '/knowledge/$categorySlug/'
    | '/api/public/hooks/generate-articles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  LibraryRoute: typeof LibraryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCvEnhanceRoute: typeof ApiCvEnhanceRoute
  ToolsToolIdRoute: typeof ToolsToolIdRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  KnowledgeCategorySlugArticleSlugRoute: typeof KnowledgeCategorySlugArticleSlugRoute
  KnowledgeCategorySlugIndexRoute: typeof KnowledgeCategorySlugIndexRoute
  ApiPublicHooksGenerateArticlesRoute: typeof ApiPublicHooksGenerateArticlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolId': {
      id: '/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof ToolsToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cv-enhance': {
      id: '/api/cv-enhance'
      path: '/api/cv-enhance'
      fullPath: '/api/cv-enhance'
      preLoaderRoute: typeof ApiCvEnhanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/declarations': {
      id: '/_authenticated/declarations'
      path: '/declarations'
      fullPath: '/declarations'
      preLoaderRoute: typeof AuthenticatedDeclarationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/knowledge/$categorySlug/': {
      id: '/knowledge/$categorySlug/'
      path: '/knowledge/$categorySlug'
      fullPath: '/knowledge/$categorySlug/'
      preLoaderRoute: typeof KnowledgeCategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$categorySlug/$articleSlug': {
      id: '/knowledge/$categorySlug/$articleSlug'
      path: '/knowledge/$categorySlug/$articleSlug'
      fullPath: '/knowledge/$categorySlug/$articleSlug'
      preLoaderRoute: typeof KnowledgeCategorySlugArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/library': {
      id: '/_authenticated/admin/library'
      path: '/admin/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AuthenticatedAdminLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/knowledge': {
      id: '/_authenticated/admin/knowledge'
      path: '/admin/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/generate-articles': {
      id: '/api/public/hooks/generate-articles'
      path: '/api/public/hooks/generate-articles'
      fullPath: '/api/public/hooks/generate-articles'
      preLoaderRoute: typeof ApiPublicHooksGenerateArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDeclarationsRoute: typeof AuthenticatedDeclarationsRoute
  AuthenticatedAdminKnowledgeRoute: typeof AuthenticatedAdminKnowledgeRoute
  AuthenticatedAdminLibraryRoute: typeof AuthenticatedAdminLibraryRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDeclarationsRoute: AuthenticatedDeclarationsRoute,
  AuthenticatedAdminKnowledgeRoute: AuthenticatedAdminKnowledgeRoute,
  AuthenticatedAdminLibraryRoute: AuthenticatedAdminLibraryRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  LibraryRoute: LibraryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCvEnhanceRoute: ApiCvEnhanceRoute,
  ToolsToolIdRoute: ToolsToolIdRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  KnowledgeCategorySlugArticleSlugRoute: KnowledgeCategorySlugArticleSlugRoute,
  KnowledgeCategorySlugIndexRoute: KnowledgeCategorySlugIndexRoute,
  ApiPublicHooksGenerateArticlesRoute: ApiPublicHooksGenerateArticlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
